"""add phone number

Revision ID: 25980b6c4051
Revises: d642cc867b8a
Create Date: 2022-06-07 23:36:43.442654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25980b6c4051'
down_revision = 'd642cc867b8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
